name: NETCore

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_VERSION: '5.0.100-rc.1.20452.10'           # https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/5.0/releases.json
  BuildConfig: Release

jobs:
    build:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      
      - name: Versioning
        uses: dotnet/nbgv@master
        id: nbgv

      - name: Version Info
        run: |
          echo 'SemVer2: ${{ steps.nbgv.outputs.SemVer2 }}'

      - name: 'Install .NET SDK'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration ${{ env.BuildConfig }} /p:Version=${{ steps.nbgv.outputs.AssemblyVersion }}

      - name: Pack NuGet
        run: dotnet pack --configuration ${{ env.BuildConfig }} /p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }}

      - name: Push to NuGet
        run: dotnet nuget push **/*.nupkg
                --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
                --source https://api.nuget.org/v3/index.json
                --no-symbols 1