name: NETCore

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

env:
  # https://www.nuget.org/packages/GitVersion.Tool
  BuildConfig: Release
  PackageProjects: AspNetCore.CloudFlare/BenjaminAbt.AspNetCore.CloudFlare.csproj

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      
      - uses: aarnott/nbgv@v0.3 # https://github.com/AArnott/nbgv
        id: nbgv

      - name: Versioning
        run: echo ${{ steps.nbgv.outputs.SemVer2 }}

      - name: Build with dotnet
        run: dotnet build
              --configuration ${{ env.BuildConfig }}
              /p:Version=${{ steps.nbgv.outputs.AssemblyVersion }}

      - name: Test with dotnet
        run: dotnet test 

      - name: Pack NuGet
        run: dotnet pack ${{ env.PackageProjects }}
              --configuration ${{ env.BuildConfig }}
              /p:Version=${{ steps.nbgv.outputs.NuGetPackageVersion }}

      - name: Push to NuGet
        run: dotnet nuget push **/*.nupkg
                --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
                --source https://api.nuget.org/v3/index.json
                --no-symbols 1